import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createService} from '../server/service.mjs';
import {createHttpServer,authenticatedFetch as fetch} from './helpers/http-fixture.mjs';

test('scene and look HTTP routes keep validation and review gates in the backend',async t=>{
  const dir=await mkdtemp(path.join(tmpdir(),'aiframe-scene-http-'));
  await mkdir(path.join(dir,'projects'));await mkdir(path.join(dir,'dist'));
  const service=await createService({dataDir:path.join(dir,'projects'),providers:{importImage:async p=>`/media/${p.id}/uploaded.png`}});
  const server=await createHttpServer({service,config:{public:()=>({})},dataDir:dir,distDir:path.join(dir,'dist')});
  t.after(async()=>{await server.close();await service.close();await rm(dir,{recursive:true,force:true});});
  const request=async(endpoint,payload={},method='POST')=>{
    const response=await fetch(server.url+endpoint,{method,headers:{'X-Local-Client':'aiframe','content-type':'application/json'},body:JSON.stringify(payload)});
    return {status:response.status,body:await response.json()};
  };
  const {body:project}=await request('/api/demo');const base=`/api/projects/${project.id}`,cid=project.characters[0].id;
  const batchTarget = project.characters.slice(0, 2);
  const batchPayload = { kind: 'character', action: 'generate', targetIds: batchTarget.map(item => item.id), expectedVersions: Object.fromEntries(batchTarget.map(item => [item.id, item.version])) };
  const deniedBatch = await fetch(server.url + `${base}/batch`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(batchPayload) });
  assert.equal(deniedBatch.status, 403);
  const batchResponse = await request(`${base}/batch`, batchPayload);
  assert.equal(batchResponse.status, 200);
  assert.deepEqual(batchResponse.body.accepted, batchTarget.map(item => item.id));
  assert.equal(batchResponse.body.createdJobIds.length, 2);
  const catalog=await (await fetch(server.url+'/api/board-templates')).json();
  assert.equal(catalog.defaultTemplateId,'classic-nine');assert.deepEqual(catalog.templates.map(item=>[item.id,item.shotCapacity,item.lookCapacity]),[['classic-nine',9,2],['eight-one',8,1],['three-three',3,3]]);
  const segment=project.segments[0];
  const preference=await request(`${base}/segments/${segment.id}`,{boardTemplateId:'eight-one'},'PATCH');
  assert.equal(preference.status,200);assert.equal(preference.body.segments[0].boardTemplateId,'eight-one');assert.deepEqual(preference.body.segments[0].shots,segment.shots);
  assert.equal((await request(`${base}/segments/${segment.id}`,{boardTemplateId:'unknown'},'PATCH')).status,400);
  const invalidPreview=await request(`${base}/segments/${segment.id}/preview`,{templateId:'unknown'});assert.equal(invalidPreview.status,400);assert.equal(invalidPreview.body.code,'INVALID_INPUT');
  const unauthorized=await fetch(server.url+`${base}/segments/${segment.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:'{"boardTemplateId":"three-three"}'});assert.equal(unauthorized.status,403);
  const created=await request(base+'/scenes',{name:'晚宴',description:'换装后'});assert.equal(created.status,200);
  const scene=created.body.scenes.at(-1);
  const lookInput={sceneId:scene.id,characterId:cid,name:'晚礼服',appearance:'绿色长裙'};
  assert.equal((await request(base+'/looks',lookInput)).status,409);
  await request(`${base}/characters/${cid}/upload`,{dataUrl:'data:image/png;base64,AA=='});await request(`${base}/characters/${cid}/approve`);
  const lookResult=await request(base+'/looks',lookInput);assert.equal(lookResult.status,200);const look=lookResult.body.looks.at(-1);
  assert.equal((await request(base+'/looks',lookInput)).status,409);
  const uploaded=await request(`${base}/looks/${look.id}/upload`,{dataUrl:'data:image/png;base64,AA==',expectedVersion:look.version});assert.equal(uploaded.status,200);
  const current=uploaded.body.looks.at(-1);
  assert.equal((await request(`${base}/looks/${look.id}/approve`,{reviewedVersion:look.version})).status,409);
  const reviewed=await request(`${base}/looks/${look.id}/approve`,{reviewedVersion:current.version});assert.equal(reviewed.body.looks.at(-1).approved,true);
  const edited=await request(`${base}/looks/${look.id}`,{appearance:'蓝色长裙'},'PATCH');assert.equal(edited.status,200);assert.equal(edited.body.looks.at(-1).approved,false);
  assert.equal((await request(`${base}/looks/${look.id}`,{reference:'/media/fake.png'},'PATCH')).status,400);
  const sceneEdited=await request(`${base}/scenes/${scene.id}`,{description:'露台'},'PATCH');assert.equal(sceneEdited.status,200);
  const shot=project.segments[0].shots[0];const moved=await request(`${base}/shots/${shot.id}`,{sceneId:scene.id},'PATCH');assert.equal(moved.status,200);assert.equal(moved.body.segments[0].shots[0].sceneId,scene.id);
  assert.equal((await request(`${base}/shots/${shot.id}`,{sceneId:'missing'},'PATCH')).status,400);
});
